######################################################################
# Automatically generated by qmake (3.1) Tue Feb 21 15:10:10 2017
######################################################################

TEMPLATE = app
TARGET = boardServer
INCLUDEPATH += .

QT += core network sql widgets

# Input
HEADERS +=  network.h \
            database.h \  
            storage.h
SOURCES +=  main.cpp \
            network.cpp \
            storage.cpp
